My First Project on the dataset of titanic

In [218]:
import pandas as pd 
import numpy as np
import matplotlib as mpt
import seaborn as sab

from sklearn.model_selection import train_test_split,StratifiedGroupKFold,GridSearchCV

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.pipeline import Pipeline,make_pipeline

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [219]:
data_gender=pd.read_csv("gender_submission.csv")
data_test=pd.read_csv("test.csv")
data_train=pd.concat([pd.read_csv("train.csv"),data_test])

In [221]:
data_train.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0.0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0.0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0.0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1.0,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1.0,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [222]:
data_train=data_train.drop(columns="Name")

In [223]:
array=["male","female"]
chnage_sex=OrdinalEncoder(categories=[array])
data_train["Sex"]=chnage_sex.fit_transform(data_train[["Sex"]])

In [224]:
data_train.head(10)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,0.0,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,1.0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,1.0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,1.0,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,0.0,35.0,0,0,373450,8.0500,NaN,S
5,6,0.0,3,0.0,NaN,0,0,330877,8.4583,NaN,Q
6,7,0.0,1,0.0,54.0,0,0,17463,51.8625,E46,S
7,8,0.0,3,0.0,2.0,3,1,349909,21.0750,NaN,S
8,9,1.0,3,1.0,27.0,0,2,347742,11.1333,NaN,S
9,10,1.0,2,1.0,14.0,1,0,237736,30.0708,NaN,C

In [225]:
data=SimpleImputer(strategy="mean",add_indicator=True)
data_train["Age"]=data.fit_transform(data_train[["Age"]])

In [ ]:
#survived_null=SimpleImputer(strategy="constant",fill_value=0.5)
#data_train["Survived"]=survived_null.fit_transform(data_train[["Survived"]])

In [226]:
data_train = data_train.dropna(subset=["Survived"])

In [227]:
data_train.head(10)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,0.0,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,1.0,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,1.0,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,1.0,35.000000,1,0,113803,53.1000,C123,S
4,5,0.0,3,0.0,35.000000,0,0,373450,8.0500,NaN,S
5,6,0.0,3,0.0,29.881138,0,0,330877,8.4583,NaN,Q
6,7,0.0,1,0.0,54.000000,0,0,17463,51.8625,E46,S
7,8,0.0,3,0.0,2.000000,3,1,349909,21.0750,NaN,S
8,9,1.0,3,1.0,27.000000,0,2,347742,11.1333,NaN,S
9,10,1.0,2,1.0,14.000000,1,0,237736,30.0708,NaN,C

In [228]:
data_train=data_train.drop(columns="Ticket")

In [229]:
data_train.head(10)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,1,0.0,3,0.0,22.000000,1,0,7.2500,NaN,S
1,2,1.0,1,1.0,38.000000,1,0,71.2833,C85,C
2,3,1.0,3,1.0,26.000000,0,0,7.9250,NaN,S
3,4,1.0,1,1.0,35.000000,1,0,53.1000,C123,S
4,5,0.0,3,0.0,35.000000,0,0,8.0500,NaN,S
5,6,0.0,3,0.0,29.881138,0,0,8.4583,NaN,Q
6,7,0.0,1,0.0,54.000000,0,0,51.8625,E46,S
7,8,0.0,3,0.0,2.000000,3,1,21.0750,NaN,S
8,9,1.0,3,1.0,27.000000,0,2,11.1333,NaN,S
9,10,1.0,2,1.0,14.000000,1,0,30.0708,NaN,C

In [230]:
data_train["Embarked"].isna().sum()

np.int64(2)

In [231]:
embark_nan=SimpleImputer(strategy="most_frequent")
data_train[["Embarked"]]=embark_nan.fit_transform(data_train[["Embarked"]])

In [232]:
data_train["Embarked"].unique()

array(['S', 'C', 'Q'], dtype=object)

In [233]:
array_embrk=["S","C","Q"]
embark_convert=OrdinalEncoder(categories=[array_embrk])
data_train["Embarked"]=embark_convert.fit_transform(data_train[["Embarked"]])

In [234]:
data_train.head(10)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,1,0.0,3,0.0,22.000000,1,0,7.2500,NaN,0.0
1,2,1.0,1,1.0,38.000000,1,0,71.2833,C85,1.0
2,3,1.0,3,1.0,26.000000,0,0,7.9250,NaN,0.0
3,4,1.0,1,1.0,35.000000,1,0,53.1000,C123,0.0
4,5,0.0,3,0.0,35.000000,0,0,8.0500,NaN,0.0
5,6,0.0,3,0.0,29.881138,0,0,8.4583,NaN,2.0
6,7,0.0,1,0.0,54.000000,0,0,51.8625,E46,0.0
7,8,0.0,3,0.0,2.000000,3,1,21.0750,NaN,0.0
8,9,1.0,3,1.0,27.000000,0,2,11.1333,NaN,0.0
9,10,1.0,2,1.0,14.000000,1,0,30.0708,NaN,1.0

In [235]:
data_train=data_train.drop(columns="Cabin")

In [236]:
data_train.head(10)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0.0,3,0.0,22.000000,1,0,7.2500,0.0
1,2,1.0,1,1.0,38.000000,1,0,71.2833,1.0
2,3,1.0,3,1.0,26.000000,0,0,7.9250,0.0
3,4,1.0,1,1.0,35.000000,1,0,53.1000,0.0
4,5,0.0,3,0.0,35.000000,0,0,8.0500,0.0
5,6,0.0,3,0.0,29.881138,0,0,8.4583,2.0
6,7,0.0,1,0.0,54.000000,0,0,51.8625,0.0
7,8,0.0,3,0.0,2.000000,3,1,21.0750,0.0
8,9,1.0,3,1.0,27.000000,0,2,11.1333,0.0
9,10,1.0,2,1.0,14.000000,1,0,30.0708,1.0

In [237]:
data_y=data_train.pop(item="Survived")
#X_test,X_train,y_test,y_train=train_test_split(data_x,data_y,test_size=0.3,random_state=40)

In [238]:
data_y

0      0.0
1      1.0
2      1.0
3      1.0
4      0.0
      ...
886    0.0
887    1.0
888    0.0
889    1.0
890    0.0
Name: Survived, Length: 891, dtype: float64

In [239]:
data_x=data_train
data_x.isna().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [240]:
fare_null=SimpleImputer(strategy="mean")
data_x[["Fare"]]=fare_null.fit_transform(data_x[["Fare"]])

In [241]:
data_y.isna().sum()

np.int64(0)

In [242]:
data_y

0      0.0
1      1.0
2      1.0
3      1.0
4      0.0
      ...
886    0.0
887    1.0
888    0.0
889    1.0
890    0.0
Name: Survived, Length: 891, dtype: float64

In [243]:
data_x=data_x.drop(columns="PassengerId")

In [244]:
data_x

     Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0         3  0.0  22.000000      1      0   7.2500       0.0
1         1  1.0  38.000000      1      0  71.2833       1.0
2         3  1.0  26.000000      0      0   7.9250       0.0
3         1  1.0  35.000000      1      0  53.1000       0.0
4         3  0.0  35.000000      0      0   8.0500       0.0
..      ...  ...        ...    ...    ...      ...       ...
886       2  0.0  27.000000      0      0  13.0000       0.0
887       1  1.0  19.000000      0      0  30.0000       0.0
888       3  1.0  29.881138      1      2  23.4500       0.0
889       1  0.0  26.000000      0      0  30.0000       1.0
890       3  0.0  32.000000      0      0   7.7500       2.0

[891 rows x 7 columns]

In [245]:
X_test,X_train,y_test,y_train=train_test_split(data_x,data_y,test_size=0.3,random_state=40)

In [246]:
X_test.shape

(623, 7)

In [247]:
y_test.shape

(623,)

In [248]:
y_train.shape

(268,)

In [249]:
X_train.shape

(268, 7)

Lest apply the ML  model that i have learned

In [250]:
X_train.isna().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

KN Neighbour ALGO

In [252]:
Kn_model=KNeighborsClassifier(n_neighbors=8)
kn_fit=Kn_model.fit(X_train,y_train)

In [255]:
y_pred=kn_fit.predict(X_test)

In [254]:
kn_fit.score(X_test,y_test)

0.7078651685393258

In [259]:
#kn model analysis
confusion_matrix=confusion_matrix(y_test,y_pred)
confusion_matrix

TypeError: 'numpy.ndarray' object is not callable

In [260]:
classification_report=classification_report(y_test,y_pred)
classification_report

'              precision    recall  f1-score   support\n\n         0.0       0.73      0.86      0.79       393\n         1.0       0.65      0.44      0.53       230\n\n    accuracy                           0.71       623\n   macro avg       0.69      0.65      0.66       623\nweighted avg       0.70      0.71      0.69       623\n'

Desision Tree ALGO

In [261]:
decision_tree=DecisionTreeClassifier(criterion='entropy',min_samples_split=20,max_depth=30,ccp_alpha=0.04)

In [262]:
decision_model=decision_tree.fit(X_train,y_train)

In [263]:
decision_model_score=decision_model.score(X_test,y_test)

In [264]:
decision_model_score

0.78330658105939

In [266]:
decision_model_predict=decision_model.predict(X_test)

Random Forest ALGO

In [ ]:
random_forest=RandomForestClassifier()

In [281]:
random_forest_model=random_forest.fit(X_train,y_train)

In [282]:
random_forest_score=random_forest_model.score(X_test,y_test)
random_forest_score

0.7752808988764045

In [291]:
param=[{#"criterion":["entropy","gini","log_loss"],
        #"max_depth":[10,30,20],
        "min_samples_split":[10,8,12],
        "ccp_alpha":[0.04,0.05,0.06],
        "n_estimators":[500,1000,1500]}]

In [292]:
from sklearn.model_selection import GridSearchCV

In [293]:
rand_multi=GridSearchCV(random_forest,param,cv=2,n_jobs=-1,scoring="accuracy")

In [294]:
rand_multi_model=rand_multi.fit(X_train,y_train)

In [295]:
rand_multi_model_score=rand_multi_model.score(X_test,y_test)

In [296]:
rand_multi_model_score

0.8138041733547352

In [297]:
rand_multi.best_estimator_

RandomForestClassifier(ccp_alpha=0.04, criterion='entropy', max_depth=60,
                       min_samples_split=10, n_estimators=500)

Naive Bayes ALGO

In [298]:
Nb_algo=GaussianNB(var_smoothing=0.15)

In [299]:
Nb_algo_model=Nb_algo.fit(X_train,y_train)

In [300]:
Nb_algo_model.score(X_test,y_test)

0.6709470304975923

SUPPORT VECTOR MACHINE ALGO

In [304]:
param_for_SVM=[{
    "kernel":["poly","linear"],
    "C":[0.1,0.2],
    "gamma":[1,2]
}]

In [ ]:
#SVM_algo=SVC()

#SVM_grid_search=GridSearchCV(SVM_algo,param_for_SVM,scoring="accuracy",n_jobs=-1)

SVM_algo=SVC(kernel='linear',C=0.1,gamma=1)

In [ ]:
#svm_model_eval=SVM_grid_search.fit(X_train,y_train)

svm_model_eval=SVM_algo.fit(X_train,y_train)

In [ ]:
svm_model_eval.score(X_test,y_test)

0.7865168539325843